### ISSUE TITLE
problem with synthms

### ISSUE THREAD

**Issue by lmorabit** [darafferty/losito#4]
Hello,

I've installed losito and wanted to try out synthms, but even when I run with -h I get the following error:

Traceback (most recent call last):
  File "/beegfs/lofar/morabito/AGN_detection/losito/bin/synthms", line 4, in <module>
    __import__('pkg_resources').run_script('LoSiTo==1.1', 'synthms')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1461, in run_script
    code = compile(source, script_filename, 'exec')
  File "/beegfs/lofar/morabito/AGN_detection/losito/lib/python2.7/site-packages/LoSiTo-1.1-py2.7.egg/EGG-INFO/scripts/synthms", line 188
    R = np.identity(3) + skew + skew @ skew /(1 + np.dot(a, b))
                                     ^
SyntaxError: invalid syntax

This is with python 2.7.5.

Any help you could provide would be much appreciated!

**Comment by henedler** [comment]
Hi Lea, 
could you try it with Python 3? The script is not tested with Python 2.
Let me know if it works.

**Comment by lmorabit** [comment]
I can try, but will have to see if I have all of the requisite software / packages in a singularity image together somewhere.

It might be worthwhile putting in the documentation / README file that this is for python3!
